# Generated by Django 4.1.7 on 2023-02-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examples", "0002_personaldata_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personaldata",
            name="gender",
            field=models.CharField(
                choices=[("Mr.", "Mr."), ("Mrs.", "Mrs."), ("unknown", "pending")],
                default="Mr.",
                max_length=10,
            ),
        ),
    ]
