# Generated by Django 4.1.7 on 2023-02-23 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("examples", "0003_alter_personaldata_gender"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="personaldata",
            options={"verbose_name": "Osoba", "verbose_name_plural": "Osoby"},
        ),
    ]
