# Generated by Django 4.1.7 on 2023-02-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={"verbose_name": "Notatka", "verbose_name_plural": "Notatki"},
        ),
        migrations.AddField(
            model_name="note",
            name="status",
            field=models.CharField(
                choices=[
                    ("opublikowana", "published"),
                    ("nieopublikowana", "not-published"),
                    ("w redakcji", "pending"),
                ],
                default="enter status",
                max_length=40,
            ),
        ),
    ]
