# Generated by Django 4.1.5 on 2023-02-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_alter_note_options_note_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="creation_datetime",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
