# Generated by Django 4.1.7 on 2023-02-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_alter_note_creation_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="status",
            field=models.CharField(
                choices=[
                    ("pub", "published"),
                    ("unpub", "unpublished"),
                    ("redac", "pending"),
                ],
                default="enter status",
                max_length=40,
            ),
        ),
    ]
